server:
  port: 8888

endpoints:
  enabled: true
  beans:
    enabled: true
    sensitive: false
  configprops:
    sensitive: false
  env:
    sensitive: false
  actuator:
    sensitive: false

encrypt:
  keyStore:
    location: classpath:server.jks
    password: letmein
#    alias: mykey
    secret: changeme

---
spring.profiles: localstandalone

spring:
  cloud:
    config:
      server:
        git:
          # Serve a local clone of whatever repo
          uri: file:/Users/bplies/Documents/workspace/spring-cloud-config/spring-cloud-config-server/target/repos/encrypt-repo

security.user.password: test
